data: 'ntu_skeleton'
data_param:
  train_data_param:
    data_path: ../data_files/ntu_60/xsub/train_data_joint.npy
    label_path: ../data_files//ntu_60/xsub/train_label.pkl
    random_choose: True
    center_choose: False
    window_size: 150
    final_size: 128
    num_skip_frame:
    decouple_spatial: False
  val_data_param:
    data_path: ../data_files/ntu_60/xsub/val_data_joint.npy
    label_path: ../data_files/ntu_60/xsub/val_label.pkl
    random_choose: False
    center_choose: True
    window_size: 150
    final_size: 128
    num_skip_frame:
    decouple_spatial: False

# model
model: 'gptnet_lay'
class_num: 60
model_param:
  num_point: 25
  num_frame: 128
  num_subset_S: 3
  num_subset_T: 3
  num_person: 2
  glo_reg_s: True
  dropout: 0
  attentiondrop: 0
  dropout2d: 0
  directed: True
  TCN: True
  kernel_size: 7
#  config: [ [64, 64, 16, 1],[64, 128, 32, 1],
#            [128, 256, 64, 1], [256, 256, 64, 1],
#  ]
  use_SSL: False
  SSL_option: {'mask': False, 'pred_S': False, 'pred_T': False, 'reverse': False, 'Contra': False}
  SSL_weight: {'mask': 0.1, 'pred_S': 0.1, 'pred_T': 0.1, 'reverse': 0.1, 'Contra': 0.1}
  mask_divide: [0.8, 0.1, 0.1]
  var: 0.5
  num_seg: 3

  config: [ [64, 64, 16, 1], [64, 64, 16, 1],
            [64, 128, 32, 1], [128, 128, 32, 1],
            [128, 256, 64, 1], [256, 256, 64, 1],
            [256, 256, 64, 1], [256, 256, 64, 1],
  ]


train: 'classify'
mode: 'train_val'
loss: 'cross_entropy'
batch_size: 32
worker: 32
pin_memory: False
num_epoch_per_save: 200
model_saved_name: './work_dir/ntu60/gpt_lay_NoSSL'
last_model:
pre_trained_model:
ignore_weights: ['fc']
label_smoothing_num: 0
mix_up_num: 0
device_id: [0,1,2,3]
cuda_visible_device: '0,1,2,3'
debug: False

# lr
lr_scheduler: 'reduce_by_epoch'
lr_param:
  step: [60, 90, 120]
#  lr_patience: 10
#  lr_threshold: 0.0001
#  lr_delay: 0
warm_up_epoch: 5
max_epoch: 150
lr: 0.1
wd: 0.0005
lr_decay_ratio: 0.1
lr_multi_keys: []

# optimizer
optimizer: 'sgd_nev'
freeze_keys: []